//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectReboot2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatchData
    {
        public System.DateTime Date { get; set; }
        public string FishName { get; set; }
        public Nullable<double> weight { get; set; }
        public string Bait { get; set; }
        public string BaitColor { get; set; }
    }
}
