//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectReboot2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WATERFEATURE
    {
        public string WaterType { get; set; }
        public Nullable<int> GPS { get; set; }
        public Nullable<int> WaterCurrent { get; set; }
        public Nullable<int> Temperature { get; set; }
    }
}
